### ISSUE TITLE
使用体験の向上

### ISSUE THREAD

**Issue by kobkaz** [arkedge/kble#73]
kbleに「行儀のよい」振る舞いをさせて、デバッグ等をしやすくしたい

今考えている改善（概ね優先順位の順）

- わかりやすいエラーメッセージをだす
  - kble本体でもtracingを有効にする 
- WebSocket接続をgracefulに終了する
  -  現状 `Connection reset without closing handshake` が出力の大半を占めている
- 子プロセスをwaitする
- SIGTERM等を受けた場合も適切に終了する
  - WebSocketのgracefulな終了や子プロセスの終了を含む
- 自動再接続
  - できれば

**Comment by KOBA789** [comment]
子プロセス wait してないっけ、と思ったらしてなかった……（質悪くてすみません）

**Comment by sksat** [comment]
これは以下でやったかんじなのかな
- #74 
- #78 
- #82 
- #90

**Comment by KOBA789** [comment]
元のアイデアをすべてやったわけではないけど、それらで部分的に実現したという認識

**Comment by kobkaz** [comment]
そうですね、一区切りでよいと思います
